config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :user
  resources :task
  root to: 'task#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  validates :name, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 50 }

  has_secure_password

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user_path(user)
    else
      puts params[:session]
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @task.save
    if @task.errors.empty?
      redirect_to task_path(@task)
    else
      puts @task.errors.full_messages
      render "new"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    if @task.errors.empty?
      redirect_to task_path(@task)
    else
      render "edit"
    end
  end

  private
    def task_params
      params.require(:task).permit(:name, :description, :start_time, :end_time)
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.empty?
      redirect_to user_path(@user)
    else
        render "new"
        puts @user.errors.full_messages
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

    def logged_in?
      !current_user.nil?
    end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <h2 align='center'><%=link_to "Task list by Zol", root_path%></h2>
      </header>
      <input type="checkbox" id="nav-toggle" hidden>
      <nav class="nav">
        <label for="nav-toggle" class="nav-toggle" onclick></label>
        <ul>
          <li><%=link_to "Home", root_path%></li>
          <li><%=link_to "Add new task", new_task_path%></li>
          <li><%=link_to "Sign Up", new_user_path%></li>
          <li><%=link_to "Profile", current_user%></li>
          <li>Sign in</li>
        </ul>

      </nav>
      <%= yield %>
      <footer>
        <div class="footer">
          <i>Zol,</i>
          <i><%=Date.today.year%></i>
        </div>
      </footer>
  </body>
</html>

app/views/task/edit.html.erb
<table align='center'>
  <tr>
    <td>
      <%=form_with model: @task do |f|%>
        <p><%=f.text_field :name%></p>
        <p><%=f.text_field :description%></p>
        <p><%=f.time_field :start_time%></p>
        <p><%=f.time_field :end_time%></p>
        <p><%=f.submit "Edit task" %></p>
      <%end%>
    </td>
  </tr>
</table>

app/views/task/index.html.erb
<table align = 'center'>
  <th>ID</th>
  <th>Name</th>
  <th>Description</th>
  <th>Start at</th>
  <th>End at</th>
  <th></th>
  <th></th>
  <th></th>

  <% @tasks.each do |t|%>
    <tr>
      <td><%=link_to t.id,task_path(t.id)%></td>
      <td><%=link_to t.name,task_path(t.id)%></td>
      <td><%=t.description%></td>
      <td><%=t.start_time%></td>
      <td><%=t.end_time%></td>
      <%if t.user %>
        <td><%=t.user.name %></td>
      <%else%>
        <td>Nil</td>
      <%end%>
      <td><%= link_to "Edit", edit_task_path(t)%></td>
      <td><%= link_to "Delete", task_path(t), :method => :delete, data: {confirm:"Are you sure?"} %></td>
    </tr>
  <%end%>
</table>

app/views/task/new.html.erb
<table align='center'>
  <tr>
    <td>
      <%=form_with model: @task, url: {action: "new"} do |f|%>
        <p><%=f.text_field :name%></p>
        <p><%=f.text_field :description%></p>
        <p><%=f.time_field :start_time%></p>
        <p><%=f.time_field :end_time%></p>
        <p><%=f.submit "Add task" %></p>
      <%end%>
    </td>
  </tr>
</table>

app/views/task/show.html.erb
<table align = 'center'>
  <th>ID</th>
  <th>Name</th>
  <th>Description</th>
  <th>Start at</th>
  <th>End at</th>
  <th>User</th>
  <tr>
    <td><%=@task.id%></td>
    <td><%=@task.name%></td>
    <td><%=@task.description%></td>
    <td><%=@task.start_time%></td>
    <td><%=@task.end_time%></td>
    <td><%=link_to @task.user.name, user_path(@task.user.id)%></td>
  </tr>
</table>

app/views/user/index.html.erb
<table align = 'center'>
    <%@users.each do |f|%>
      <tr>
        <td><%=link_to f.name, user_path(f.id) %></td>
        <td><%=f.email%></td>
        <td><%= link_to "Delete", user_path(f), :method => :delete, data: {confirm:"Are you sure?"} %></td>
      </tr>
    <%end%>
</table>

app/views/user/new.html.erb
<table align='center'>
  <tr>
    <td>
      <%=form_with model: @user, url: {action: "create"} do |f|%>
        <%=f.label :name%>
        <p><%=f.text_field :name%></p>
        <%=f.label :email%>
        <p><%=f.text_field :email%></p>
        <%=f.label :password%>
        <p><%=f.password_field :password%></p>
        <%=f.label :password_confirmation%>
        <p><%=f.password_field :password_confirmation%></p>
        <p><%=f.submit "Create user" %></p>
      <%end%>
    </td>
  </tr>
</table>

app/views/user/show.html.erb
<table align = 'center'>
  <th>ID</th>
  <th>Name</th>
  <th>Email</th>
  <th>Task</th>
    <tr>
      <td><%=@user.id%></td>
      <td><%=@user.name%></td>
      <td><%=@user.email%></td>
      <td><%=@user.tasks.name%></td>
    </tr>
</table>